<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.ServiceBus"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="xunit.v3.extensibility.core"/>
        <PackageReference Include="Azure.Messaging.ServiceBus"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ServiceBusToolset.Application\ServiceBusToolset.Application.csproj"/>
    </ItemGroup>

</Project>
