<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.ServiceBus" Version="4.10.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2"/>
        <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2"/>
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ServiceBusToolset.Application\ServiceBusToolset.Application.csproj"/>
    </ItemGroup>

</Project>
