using Azure.Messaging.ServiceBus;
using ServiceBusToolset.TestHarness.Common.Commands;
using ServiceBusToolset.TestHarness.Common.Logging;
using ServiceBusToolset.TestHarness.Common.ServiceBus;

namespace ServiceBusToolset.TestHarness.DeadLetters.GenerateDlq;

public sealed class GenerateDlqCommandHandler(IServiceBusClientFactory clientFactory, IConsoleOutput output)
    : BaseCommandHandler<GenerateDlqCliCommand>(output)
{
    private const int BatchSize = 10;

    protected override async Task<int> ExecuteCoreAsync(GenerateDlqCliCommand command, bool verbose,
                                                        CancellationToken cancellationToken = default)
    {
        Output.Info($"Generating {command.Count} dead-letter messages in '{command.Queue}'...");

        var factory = new DeadLetterMessageFactory();
        var specs = factory.CreateSpecs(command.Count);

        var hasTelemetry = !string.IsNullOrEmpty(command.AppInsightsConnectionString);
        using var telemetryGenerator = hasTelemetry
            ? new TelemetryGenerator(command.AppInsightsConnectionString!)
            : null;

        if (hasTelemetry)
        {
            Output.Info("Application Insights telemetry generation enabled.");
        }

        var random = new Random(42);
        var traceIdMap = new Dictionary<int, (string TraceId, DeadLetterSpec Spec)>();

        for (var i = 0; i < specs.Count; i++)
        {
            if (specs[i].Profile != TelemetryProfile.NoOperationId)
            {
                var traceId = GenerateHexString(random, 32);
                traceIdMap[i] = (traceId, specs[i]);
            }
        }

        await using var client = clientFactory.CreateClient(command.Namespace);
        await using var sender = client.CreateSender(command.Queue);
        await using var receiver = client.CreateReceiver(command.Queue);

        var totalProcessed = 0;

        for (var batchStart = 0; batchStart < specs.Count; batchStart += BatchSize)
        {
            var batch = specs.Skip(batchStart).Take(BatchSize).ToList();
            var batchIndices = Enumerable.Range(batchStart, batch.Count).ToList();

            var messages = new List<ServiceBusMessage>();
            for (var i = 0; i < batch.Count; i++)
            {
                var spec = batch[i];
                var msg = new ServiceBusMessage(spec.Body) { Subject = spec.Subject };

                var globalIndex = batchStart + i;
                if (traceIdMap.TryGetValue(globalIndex, out var entry))
                {
                    var spanId = GenerateHexString(random, 16);
                    msg.ApplicationProperties["Diagnostic-Id"] = $"00-{entry.TraceId}-{spanId}-01";
                }

                messages.Add(msg);
            }

            await sender.SendMessagesAsync(messages, cancellationToken);

            var received = await receiver.ReceiveMessagesAsync(batch.Count,
                                                               TimeSpan.FromSeconds(10),
                                                               cancellationToken);

            foreach (var msg in received)
            {
                var spec = batch.FirstOrDefault(s => s.Subject == msg.Subject && s.Body == msg.Body.ToString());
                var reason = spec?.DeadLetterReason ?? "TestGenerated";
                var description = "Generated by TestHarness for testing";

                await receiver.DeadLetterMessageAsync(msg, reason, description, cancellationToken);
            }

            // Generate telemetry for this batch
            if (telemetryGenerator != null)
            {
                var telemetryItems = batchIndices
                    .Where(idx => traceIdMap.ContainsKey(idx) && traceIdMap[idx].Spec.Profile is not (TelemetryProfile.NoOperationId or TelemetryProfile.NoTelemetry))
                    .Select(idx => traceIdMap[idx])
                    .ToList();

                if (telemetryItems.Count > 0)
                {
                    telemetryGenerator.GenerateTelemetry(telemetryItems);
                }
            }

            totalProcessed += received.Count;
            Output.Progress($"Processed {totalProcessed}/{specs.Count} messages...");

            Output.Verbose($"  Batch {batchStart / BatchSize + 1}: sent {batch.Count}, received {received.Count}",
                            verbose);
        }

        Console.WriteLine();
        Output.Success($"Successfully dead-lettered {totalProcessed} messages.");
        Console.WriteLine();

        PrintSummary(specs);

        if (hasTelemetry)
        {
            PrintTelemetryProfileDistribution(specs);
            Console.WriteLine();
            Output.Warning("Note: Application Insights telemetry may take 2-5 minutes to become available for querying.");
        }

        return 0;
    }

    private void PrintSummary(List<DeadLetterSpec> specs)
    {
        var categories = specs
                         .GroupBy(s => new { s.Subject, s.DeadLetterReason })
                         .OrderByDescending(g => g.Count())
                         .Take(20)
                         .Select(g => new[] { g.Key.Subject, g.Key.DeadLetterReason, g.Count().ToString() });

        Output.Table(["Subject", "Dead Letter Reason", "Count"], categories);
    }

    private void PrintTelemetryProfileDistribution(List<DeadLetterSpec> specs)
    {
        var distribution = specs
            .GroupBy(s => s.Profile)
            .OrderBy(g => g.Key)
            .Select(g => new[] { g.Key.ToString(), g.Count().ToString(), $"{100.0 * g.Count() / specs.Count:F1}%" });

        Output.Table(["Telemetry Profile", "Count", "Percentage"], distribution);
    }

    private static string GenerateHexString(Random random, int length)
    {
        Span<byte> bytes = stackalloc byte[length / 2];
        random.NextBytes(bytes);
        return Convert.ToHexStringLower(bytes);
    }
}
