<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Xunit.v3.ParallelTestFramework"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="System.Reactive"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ServiceBusToolset.Application\ServiceBusToolset.Application.csproj"/>
        <ProjectReference Include="..\..\src\ServiceBusToolset.CLI\ServiceBusToolset.CLI.csproj"/>
        <ProjectReference Include="..\ServiceBusToolset.IntegrationTesting\ServiceBusToolset.IntegrationTesting.csproj"/>
    </ItemGroup>

</Project>
