<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions"/>
        <PackageReference Include="Mediator.SourceGenerator">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Ardalis.Result"/>
        <PackageReference Include="Azure.Identity"/>
        <PackageReference Include="Azure.Messaging.ServiceBus"/>
        <PackageReference Include="Azure.Monitor.Query"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="System.Reactive"/>
        <PackageReference Include="DynamicData"/>
    </ItemGroup>

</Project>
