<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.ServiceBus" Version="4.4.0"/>
        <PackageReference Include="xunit.v3" Version="1.1.0"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0"/>
        <PackageReference Include="NSubstitute" Version="5.3.0"/>
        <PackageReference Include="Shouldly" Version="4.2.1"/>
        <PackageReference Include="System.Reactive" Version="6.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ServiceBusToolset.Application\ServiceBusToolset.Application.csproj"/>
    </ItemGroup>

</Project>
